<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-08T12:36:33 PDT" name="Default suite" finished-at="2023-04-08T12:36:44 PDT" duration-ms="10370">
    <groups>
    </groups>
    <test started-at="2023-04-08T12:36:33 PDT" name="Default test" finished-at="2023-04-08T12:36:44 PDT" duration-ms="10370">
      <class name="xyzFinalLuc10.MyClass">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:xyzFinalLuc10.MyClass@3a43d133]" started-at="2023-04-08T12:36:33 PDT" name="mySetup" finished-at="2023-04-08T12:36:38 PDT" duration-ms="4504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="testOne()[pri:0, instance:xyzFinalLuc10.MyClass@3a43d133]" started-at="2023-04-08T12:36:38 PDT" name="testOne" finished-at="2023-04-08T12:36:43 PDT" duration-ms="5048" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [10] but found [73400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [10] but found [73400]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at xyzFinalLuc10.MyClass.testOne(MyClass.java:42)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method is-config="true" signature="theEnd()[pri:0, instance:xyzFinalLuc10.MyClass@3a43d133]" started-at="2023-04-08T12:36:43 PDT" name="theEnd" finished-at="2023-04-08T12:36:44 PDT" duration-ms="762" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- theEnd -->
      </class> <!-- xyzFinalLuc10.MyClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
